def foo():
    raise Exception('ERROR! Foo should be mocked')
